// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>TestXMLRead</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>True</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Concurrent;

namespace TestXMLRead
{
	using System;
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System.Collections;
	using System.Xml.Schema;
	using System.ComponentModel;
	using System.IO;
	using System.Text;
	using System.Collections.Generic;
	using System.Runtime.Serialization;


	#region Base entity class
	public partial class EntityBase<T>
	{

		private static System.Xml.Serialization.XmlSerializer serializer;

		private static System.Xml.Serialization.XmlSerializer Serializer
		{
			get
			{
				if ((serializer == null))
				{
					serializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
				}
				return serializer;
			}
		}

		#region Serialize/Deserialize
		/// <summary>
		/// Serializes current EntityBase object into an XML document
		/// </summary>
		/// <returns>string XML value</returns>
		public virtual string Serialize()
		{
			System.IO.StreamReader streamReader = null;
			System.IO.MemoryStream memoryStream = null;
			try
			{
				memoryStream = new System.IO.MemoryStream();
				Serializer.Serialize(memoryStream, this);
				memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
				streamReader = new System.IO.StreamReader(memoryStream);
				return streamReader.ReadToEnd();
			}
			finally
			{
				if ((streamReader != null))
				{
					streamReader.Dispose();
				}
				if ((memoryStream != null))
				{
					memoryStream.Dispose();
				}
			}
		}

		/// <summary>
		/// Deserializes workflow markup into an EntityBase object
		/// </summary>
		/// <param name="xml">string workflow markup to deserialize</param>
		/// <param name="obj">Output EntityBase object</param>
		/// <param name="exception">output Exception value if deserialize failed</param>
		/// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
		public static bool Deserialize(string xml, out T obj, out System.Exception exception)
		{
			exception = null;
			obj = default(T);
			try
			{
				obj = Deserialize(xml);
				return true;
			}
			catch (System.Exception ex)
			{
				exception = ex;
				return false;
			}
		}

		public static bool Deserialize(string xml, out T obj)
		{
			System.Exception exception = null;
			return Deserialize(xml, out obj, out exception);
		}

		public static T Deserialize(string xml)
		{
			System.IO.StringReader stringReader = null;
			try
			{
				stringReader = new System.IO.StringReader(xml);
				return ((T)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
			}
			finally
			{
				if ((stringReader != null))
				{
					stringReader.Dispose();
				}
			}
		}

		/// <summary>
		/// Serializes current EntityBase object into file
		/// </summary>
		/// <param name="fileName">full path of outupt xml file</param>
		/// <param name="exception">output Exception value if failed</param>
		/// <returns>true if can serialize and save into file; otherwise, false</returns>
		public virtual bool SaveToFile(string fileName, out System.Exception exception)
		{
			exception = null;
			try
			{
				SaveToFile(fileName);
				return true;
			}
			catch (System.Exception e)
			{
				exception = e;
				return false;
			}
		}

		public virtual void SaveToFile(string fileName)
		{
			System.IO.StreamWriter streamWriter = null;
			try
			{
				string xmlString = Serialize();
				System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
				streamWriter = xmlFile.CreateText();
				streamWriter.WriteLine(xmlString);
				streamWriter.Close();
			}
			finally
			{
				if ((streamWriter != null))
				{
					streamWriter.Dispose();
				}
			}
		}

		/// <summary>
		/// Deserializes xml markup from file into an EntityBase object
		/// </summary>
		/// <param name="fileName">string xml file to load and deserialize</param>
		/// <param name="obj">Output EntityBase object</param>
		/// <param name="exception">output Exception value if deserialize failed</param>
		/// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
		protected static bool LoadFromFile(string fileName, out T obj, out System.Exception exception)
		{
			exception = null;
			obj = default(T);
			try
			{
				obj = LoadFromFile(fileName);
				return true;
			}
			catch (System.Exception ex)
			{
				exception = ex;
				return false;
			}
		}

		protected static bool LoadFromFile(string fileName, out T obj)
		{
			System.Exception exception = null;
			return LoadFromFile(fileName, out obj, out exception);
		}

		protected static T LoadFromFile(string fileName)
		{
			System.IO.FileStream file = null;
			System.IO.StreamReader sr = null;
			try
			{
				file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
				sr = new System.IO.StreamReader(file);
				string xmlString = sr.ReadToEnd();
				sr.Close();
				file.Close();
				return Deserialize(xmlString);
			}
			finally
			{
				if ((file != null))
				{
					file.Dispose();
				}
				if ((sr != null))
				{
					sr.Dispose();
				}
			}
		}
		#endregion

		#region Clone method
		/// <summary>
		/// Create a clone of this T object
		/// </summary>
		public virtual T Clone()
		{
			return ((T)(this.MemberwiseClone()));
		}
		#endregion
	}
	#endregion

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd", IsNullable = false)]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ProjectData", Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
//	public partial class ProjectData : EntityBase<ProjectData>
	public partial class ProjectData : EntityBase2<ProjectData, ProjectDataCDPackagesTask>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private ProjectDataProjectInformation projectInformationField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private List<ProjectDataCDPackagesTask> cDPackagesField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ProjectDataProjectInformation ProjectInformation { get; set; }


		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Task", typeof(ProjectDataCDPackagesTask), IsNullable = false)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public List<ProjectDataCDPackagesTask> CDPackages
		{
			get
			{
				return this.cDPackagesField;
			}
			set
			{
				this.cDPackagesField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ProjectDataProjectInformation", Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	public partial class ProjectDataProjectInformation : EntityBase<ProjectDataProjectInformation>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private ProjectInfo projectField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string rootFolderField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ProjectInfo Project { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string RootFolder { get; set; }

	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd", IsNullable = true)]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ProjectInfo", Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	public partial class ProjectInfo : EntityBase<ProjectInfo>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string numberField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string descriptionField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Number { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Description { get; set; }

	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd", IsNullable = true)]
	[System.Runtime.Serialization.DataContractAttribute(Name = "PathInfo", Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	public partial class PathInfo : EntityBase<PathInfo>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string pathField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Path { get; set; }

	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ProjectDataCDPackagesTask", Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	public partial class ProjectDataCDPackagesTask : EntityBase2<ProjectDataCDPackagesTask, ProjectDataCDPackagesTaskPhase>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private List<ProjectDataCDPackagesTaskPhase> phaseField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string descriptionField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string taskField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Description { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Task { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("Phase", Order = 0)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public List<ProjectDataCDPackagesTaskPhase> Phase
		{
			get
			{
				return this.phaseField;
			}
			set
			{
				this.phaseField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ProjectDataCDPackagesTaskPhase", Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	public partial class ProjectDataCDPackagesTaskPhase : EntityBase2<ProjectDataCDPackagesTaskPhase, ProjectDataCDPackagesTaskPhaseBuilding>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private List<ProjectDataCDPackagesTaskPhaseBuilding> buildingField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string descriptionField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string phaseField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Description { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Phase { get; set; }


		[System.Xml.Serialization.XmlElementAttribute("Building", Order = 0)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public List<ProjectDataCDPackagesTaskPhaseBuilding> Building
		{
			get
			{
				return this.buildingField;
			}
			set
			{
				this.buildingField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ProjectDataCDPackagesTaskPhaseBuilding", Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	public partial class ProjectDataCDPackagesTaskPhaseBuilding : EntityBase1<ProjectDataCDPackagesTaskPhaseBuilding>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string cDFolderField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string sheetNumberFormat;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private ProjectDataCDPackagesTaskPhaseBuildingLocationAutoCAD locationAutoCADField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private ProjectDataCDPackagesTaskPhaseBuildingLocationRevit locationRevitField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string buildingField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string descriptionField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string CDFolder { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string SheetNumberFormat { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ProjectDataCDPackagesTaskPhaseBuildingLocationAutoCAD LocationAutoCAD { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public ProjectDataCDPackagesTaskPhaseBuildingLocationRevit LocationRevit { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Building { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Description { get; set; }

	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ProjectDataCDPackagesTaskPhaseBuildingLocationAutoCAD", Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	public partial class ProjectDataCDPackagesTaskPhaseBuildingLocationAutoCAD : EntityBase<ProjectDataCDPackagesTaskPhaseBuildingLocationAutoCAD>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private PathInfo sheetFileFolderField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private PathInfo xrefFolderField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private PathInfo detailFolderField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private PathInfo borderFileField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PathInfo SheetFileFolder { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PathInfo XrefFolder { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PathInfo DetailFolder { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PathInfo BorderFile { get; set; }

	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ProjectDataCDPackagesTaskPhaseBuildingLocationRevit", Namespace = "file:///D:/Users/Jeff/Documents/Programming/VisualStudioProjects/TestXMLRead/Test" +
		"XMLRead/XSD/ProjectData.xsd")]
	public partial class ProjectDataCDPackagesTaskPhaseBuildingLocationRevit : EntityBase<ProjectDataCDPackagesTaskPhaseBuildingLocationRevit>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private PathInfo cDModelFileField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private PathInfo libraryModelFileField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private PathInfo keynoteFileField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private PathInfo linkedFolderField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private PathInfo xrefFolderField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PathInfo CDModelFile { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PathInfo LibraryModelFile { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PathInfo KeynoteFile { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PathInfo LinkedFolder { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public PathInfo XrefFolder { get; set; }

	}
}
