// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>TestXMLRead</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>True</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;

namespace TestXMLRead
{
	using System;
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System.Collections;
	using System.Xml.Schema;
	using System.ComponentModel;
	using System.IO;
	using System.Text;
	using System.Collections.Generic;
	using System.Runtime.Serialization;


	#region Base entity class
	public partial class UserProjects<T>
	{

		private static System.Xml.Serialization.XmlSerializer serializer;

		private static System.Xml.Serialization.XmlSerializer Serializer
		{
			get
			{
				if ((serializer == null))
				{
					serializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
				}
				return serializer;
			}
		}

		#region Serialize/Deserialize
		/// <summary>
		/// Serializes current UserProjects object into an XML document
		/// </summary>
		/// <returns>string XML value</returns>
		public virtual string Serialize()
		{
			System.IO.StreamReader streamReader = null;
			System.IO.MemoryStream memoryStream = null;
			try
			{
				memoryStream = new System.IO.MemoryStream();
				Serializer.Serialize(memoryStream, this);
				memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
				streamReader = new System.IO.StreamReader(memoryStream);
				return streamReader.ReadToEnd();
			}
			finally
			{
				if ((streamReader != null))
				{
					streamReader.Dispose();
				}
				if ((memoryStream != null))
				{
					memoryStream.Dispose();
				}
			}
		}

		/// <summary>
		/// Deserializes workflow markup into an UserProjects object
		/// </summary>
		/// <param name="xml">string workflow markup to deserialize</param>
		/// <param name="obj">Output UserProjects object</param>
		/// <param name="exception">output Exception value if deserialize failed</param>
		/// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
		public static bool Deserialize(string xml, out T obj, out System.Exception exception)
		{
			exception = null;
			obj = default(T);
			try
			{
				obj = Deserialize(xml);
				return true;
			}
			catch (System.Exception ex)
			{
				exception = ex;
				return false;
			}
		}

		public static bool Deserialize(string xml, out T obj)
		{
			System.Exception exception = null;
			return Deserialize(xml, out obj, out exception);
		}

		public static T Deserialize(string xml)
		{
			System.IO.StringReader stringReader = null;
			try
			{
				stringReader = new System.IO.StringReader(xml);
				return ((T)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
			}
			finally
			{
				if ((stringReader != null))
				{
					stringReader.Dispose();
				}
			}
		}

		/// <summary>
		/// Serializes current UserProjects object into file
		/// </summary>
		/// <param name="fileName">full path of outupt xml file</param>
		/// <param name="exception">output Exception value if failed</param>
		/// <returns>true if can serialize and save into file; otherwise, false</returns>
		public virtual bool SaveToFile(string fileName, out System.Exception exception)
		{
			exception = null;
			try
			{
				SaveToFile(fileName);
				return true;
			}
			catch (System.Exception e)
			{
				exception = e;
				return false;
			}
		}

		public virtual void SaveToFile(string fileName)
		{
			System.IO.StreamWriter streamWriter = null;
			try
			{
				string xmlString = Serialize();
				System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
				streamWriter = xmlFile.CreateText();
				streamWriter.WriteLine(xmlString);
				streamWriter.Close();
			}
			finally
			{
				if ((streamWriter != null))
				{
					streamWriter.Dispose();
				}
			}
		}

		/// <summary>
		/// Deserializes xml markup from file into an UserProjects object
		/// </summary>
		/// <param name="fileName">string xml file to load and deserialize</param>
		/// <param name="obj">Output UserProjects object</param>
		/// <param name="exception">output Exception value if deserialize failed</param>
		/// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
		public static bool LoadFromFile(string fileName, out T obj, out System.Exception exception)
		{
			exception = null;
			obj = default(T);
			try
			{
				obj = LoadFromFile(fileName);
				return true;
			}
			catch (System.Exception ex)
			{
				exception = ex;
				return false;
			}
		}

		public static bool LoadFromFile(string fileName, out T obj)
		{
			System.Exception exception = null;
			return LoadFromFile(fileName, out obj, out exception);
		}

		public static T LoadFromFile(string fileName)
		{
			System.IO.FileStream file = null;
			System.IO.StreamReader sr = null;
			try
			{
				file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
				sr = new System.IO.StreamReader(file);
				string xmlString = sr.ReadToEnd();
				sr.Close();
				file.Close();
				return Deserialize(xmlString);
			}
			finally
			{
				if ((file != null))
				{
					file.Dispose();
				}
				if ((sr != null))
				{
					sr.Dispose();
				}
			}
		}
		#endregion

		#region Clone method
		/// <summary>
		/// Create a clone of this T object
		/// </summary>
		public virtual T Clone()
		{
			return ((T)(this.MemberwiseClone()));
		}
		#endregion
	}
	#endregion

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "File:///P:\\VisualStudioProjects\\TestXMLRead\\TestXMLRead\\XSD\\UserProjects.xsd")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "File:///P:\\VisualStudioProjects\\TestXMLRead\\TestXMLRead\\XSD\\UserProjects.xsd", IsNullable = false)]
	[System.Runtime.Serialization.DataContractAttribute(Name = "UserProjects", Namespace = "File:///P:\\VisualStudioProjects\\TestXMLRead\\TestXMLRead\\XSD\\UserProjects.xsd")]
	public partial class UserProjects : UserProjects<UserProjects>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private List<UserProjectsUser> userField;

		[System.Xml.Serialization.XmlElementAttribute("User", Order = 0)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public List<UserProjectsUser> User
		{
			get
			{
				return this.userField;
			}
			set
			{
				this.userField = value;
			}
		}

	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "File:///P:\\VisualStudioProjects\\TestXMLRead\\TestXMLRead\\XSD\\UserProjects.xsd")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "UserProjectsUser", Namespace = "File:///P:\\VisualStudioProjects\\TestXMLRead\\TestXMLRead\\XSD\\UserProjects.xsd")]
	public partial class UserProjectsUser : UserProjects<UserProjectsUser>
	{

		[EditorBrowsable(EditorBrowsableState.Never)]
		private List<UserProjectsUserProject> projectField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string nameField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Name { get; set; }


		[System.Xml.Serialization.XmlElementAttribute("Project", Order = 0)]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public List<UserProjectsUserProject> Project
		{
			get
			{
				return this.projectField;
			}
			set
			{
				this.projectField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "File:///P:\\VisualStudioProjects\\TestXMLRead\\TestXMLRead\\XSD\\UserProjects.xsd")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "UserProjectsUserProject", Namespace = "File:///P:\\VisualStudioProjects\\TestXMLRead\\TestXMLRead\\XSD\\UserProjects.xsd")]
	public partial class UserProjectsUserProject : UserProjects<UserProjectsUserProject>
	{
		[EditorBrowsable(EditorBrowsableState.Never)]
		private bool currentField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private bool currentFieldSpecified;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private bool activeField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private bool activeFieldSpecified;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string numberField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string taskField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string phaseField;

		[EditorBrowsable(EditorBrowsableState.Never)]
		private string buildingField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public bool Current { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public bool CurrentSpecified { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public bool Active { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public bool ActiveSpecified { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Number { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Task { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Phase { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Building { get; set; }

	}
}
